# 卷积层的实现

## 自定义权值

In [3]:
import tensorflow as tf
x=tf.random.normal([2,5,5,3]) # 模拟输入3通道，高度为5
# 按照[k,k,cin,cout]格式创建W张量， 4个3x3大小的卷积核
w=tf.random.normal([3,3,3,4])
# 步长为1，padding为0
out=tf.nn.conv2d(x,w,strides=1,padding=[[0,0],[0,0],[0,0],[0,0]])
out

<tf.Tensor: shape=(2, 3, 3, 4), dtype=float32, numpy=
array([[[[ -3.6205294 ,   0.12113128,   3.975155  ,   4.2588205 ],
         [ -0.92554164,   2.3715444 ,   4.1500087 ,   6.169531  ],
         [ -2.748736  ,  -3.6382902 ,   3.256584  ,   0.64921546]],

        [[ -2.1724381 ,  -7.3499985 ,   0.19241051,   0.9158553 ],
         [ -0.7582543 ,  -2.3493822 ,  -9.651439  ,  -0.18819858],
         [ -4.0487957 ,  -6.104577  ,  -7.7606187 , -15.178026  ]],

        [[-13.72019   ,  -4.0969095 ,  -4.2858624 ,   3.6450531 ],
         [ -4.384036  ,   2.6716363 ,   7.117439  ,  -3.184749  ],
         [  1.1888121 ,   3.345669  ,  13.3670635 ,  -4.0083647 ]]],


       [[[ -1.2238516 ,  -4.9339986 ,  -3.3781621 ,  -4.009736  ],
         [ -3.3000314 ,   0.08951158,  -3.2791655 ,   4.122613  ],
         [ -3.5964067 ,   3.1056929 ,   5.8081746 ,   3.0280197 ]],

        [[  0.8647205 ,  -3.25087   ,   1.3345604 ,  -5.885718  ],
         [ -5.611656  ,   1.7081407 ,   1.0742087 ,  -0.34089044]

**padding参数的格式**
```python
 padding=[[0,0],[上,下],[上,下],[0,0],[0,0]]
```
若上下各填充一个单位即
```
padding=[[0,0],[1,1],[1,1],[0,0]]
```


In [4]:
x=tf.random.normal([2,5,5,3]) # 模拟输入3通道，高度为5
# 按照[k,k,cin,cout]格式创建W张量， 4个3x3大小的卷积核
w=tf.random.normal([3,3,3,4])
# 步长为1，padding为1
out=tf.nn.conv2d(x,w,strides=1,padding=[[0,0],[1,1],[1,1],[0,0]])
out

<tf.Tensor: shape=(2, 5, 5, 4), dtype=float32, numpy=
array([[[[-6.3244872e+00,  2.2933266e-01, -1.5882653e-01,
           1.7424980e+00],
         [-3.1104689e+00, -2.7524869e+00, -6.7510486e-01,
           1.2716680e+00],
         [ 6.9353266e+00,  3.7843599e+00, -1.7463094e+00,
          -4.9824457e+00],
         [-1.4650377e+00, -6.2528509e-01, -1.9418563e+00,
           2.2172630e+00],
         [-8.3582563e+00, -2.9390628e+00, -4.1312957e-01,
          -7.5315547e-01]],

        [[-4.7451887e-01, -1.4345539e-01, -6.2943535e+00,
          -2.3832414e-01],
         [-2.8564706e+00, -2.1109004e+00, -1.8896719e+00,
          -1.2391912e+00],
         [-2.6193919e+00, -4.5793228e+00,  2.4074903e+00,
           1.7983577e+00],
         [-4.1318059e+00,  5.6728392e+00,  3.4322548e+00,
           2.0427771e+00],
         [ 1.2388480e+00, -1.2714338e-01,  1.3406159e+00,
           1.0918202e+00]],

        [[-5.2072463e+00, -4.1823125e+00, -1.0269697e+00,
           4.7673969e+00],
       

In [8]:
# 当padding='SAME'时可以得到输入、输出通大小的卷积层
# 当strides步长＞1时，设置padding='SAME'得到高、宽成1/s倍的减少

x=tf.random.normal([2,5,5,3])
w=tf.random.normal([3,3,3,4])
out1=tf.nn.conv2d(x,w,strides=1,padding='SAME')
out1

<tf.Tensor: shape=(2, 5, 5, 4), dtype=float32, numpy=
array([[[[  1.5996565 ,  -0.37725994,   2.0744011 ,  -1.9507283 ],
         [  0.02370794,   4.6912622 ,  -5.9282284 ,  -3.3402786 ],
         [ -0.41557088,   0.83452094,  -1.8215061 ,  -1.7429786 ],
         [ -3.486924  ,   1.4558746 ,   1.0992687 ,   0.60858893],
         [  4.699833  ,  -1.1230516 ,  -2.1598723 ,   0.39094013]],

        [[  1.0692463 ,  -5.3961363 ,   1.0165929 ,  -6.6751175 ],
         [ -1.0737704 ,   3.4968464 ,   0.2250531 ,   4.2545166 ],
         [  4.292991  ,   2.0232472 ,  -3.3121338 ,  -1.9753699 ],
         [ -3.5752146 ,  -3.7635856 ,   8.089906  ,  -2.0340583 ],
         [ -2.6952875 ,   0.6426771 ,   5.29564   ,   0.23095377]],

        [[ -1.2633758 ,  -3.1731763 ,   2.8984022 ,   6.759421  ],
         [  4.7566752 ,  -5.975336  ,   0.41779763,  -1.1319755 ],
         [ -0.94991374,  -3.7249947 ,   6.3909373 ,  -9.661401  ],
         [  2.0027816 ,   4.7913065 , -12.83888   ,   4.661256  ],
    

In [9]:
x=tf.random.normal([2,5,5,3])
w=tf.random.normal([3,3,3,4])
out2=tf.nn.conv2d(x,w,strides=3,padding='SAME')
out2

<tf.Tensor: shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[ 6.6389618e+00,  4.9656134e+00,  9.5027101e-01,
          -1.0452413e+01],
         [-8.5352612e-01,  3.7207146e+00, -4.7919331e+00,
          -1.7244339e+00]],

        [[-2.0570567e+00,  3.8826661e+00, -8.8624001e-02,
          -2.7297938e+00],
         [-4.8120511e-01, -6.7778497e+00,  3.0876822e+00,
          -8.1023693e-02]]],


       [[[-4.7666814e-02, -2.1229614e+01, -1.1502867e+00,
          -4.1311979e+00],
         [ 7.4135866e+00, -5.8804035e-01,  3.3095610e+00,
           4.7074361e+00]],

        [[ 1.8475413e-02,  6.9383812e+00,  8.5667772e+00,
           3.6734943e+00],
         [ 7.8917036e+00,  3.5888219e-01,  4.0520535e+00,
          -3.4515421e+00]]]], dtype=float32)>

# 卷积层类
**通过利用layers.Conv2D可以不需要手动定义卷积核W和偏执b张量**

| 参数 | 含义 |
|-----|-----|
|filters|卷积核数量参数|
|kernel_size|卷积核大小|
|strides|步长|
|padding|填充|

**创建一个4个3x3大小的卷积核，步长为1，padding方案为SAME**

```
# 利用layers.Conv2D新建卷积层
layer=layers.Conv2D(4, kernel_size=3, strides=1,padding='SAME')
```

**如果卷积核高宽不等，则需要将其改为元组类型，如下创建4个3x3大小的卷积核,竖直方向移动步长为2，水平方向移动步长为1**
```
layer=layers.Conv2D(4, kernel_size=(3,4),strides=(2,1),padding='SAME')
```

In [10]:
import tensorflow as tf
from tensorflow.keras import layers
# 创建卷积层类
x=tf.random.normal([2,5,5,3])
layer=layers.Conv2D(4, kernel_size=3, strides=1, padding='SAME')
out=layer(x) # 向前计算
out.shape # 输出张量的shape

TensorShape([2, 5, 5, 4])

In [11]:
# 返回所有待优化张量列表
layer.trainable_variables

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 4) dtype=float32, numpy=
 array([[[[ 0.0119963 , -0.2558023 , -0.19505283,  0.0826059 ],
          [ 0.22299966, -0.22749892,  0.15276456,  0.07288918],
          [ 0.0684832 , -0.09449752,  0.2959788 ,  0.11613044]],
 
         [[ 0.19506517,  0.29050717,  0.21436343, -0.21654359],
          [ 0.25795648, -0.14683722, -0.12272321, -0.06969047],
          [ 0.22993293,  0.19700286,  0.08925298,  0.18055224]],
 
         [[-0.17555985,  0.30768165, -0.05694309,  0.00183833],
          [-0.16997766, -0.16853988, -0.17461179,  0.2567534 ],
          [ 0.05512866,  0.17868292, -0.2386652 ,  0.09391412]]],
 
 
        [[[ 0.15268692,  0.02194017, -0.1472945 ,  0.22155687],
          [-0.19386816,  0.1289495 , -0.10931523, -0.1786117 ],
          [ 0.10669419,  0.02889907,  0.19042185, -0.2114523 ]],
 
         [[-0.2362556 , -0.01949885, -0.30372262, -0.22771832],
          [-0.02318135, -0.2330805 , -0.23777997, -0.27943504],
          [-0.15

# LeNet-5实战


In [34]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, optimizers, Sequential, metrics, losses

log_dir = './tensorboard_img/'
summary_writer=tf.summary.create_file_writer(log_dir)

def preprocess(x, y):
    x=tf.cast(x, dtype=tf.float32)/ 255
    y=tf.cast(y, dtype=tf.int32)
    return x,y

batchsz=128
(x, y), (x_val, y_val) = datasets.mnist.load_data()
print('datasets:', x.shape, y.shape, x.min(), x.max())

db = tf.data.Dataset.from_tensor_slices((x,y))
db = db.map(preprocess).shuffle(60000).batch(batchsz).repeat(10)

ds_val = tf.data.Dataset.from_tensor_slices((x_val, y_val))
ds_val = ds_val.map(preprocess).batch(batchsz)

network = Sequential([
    layers.Conv2D(6, kernel_size=3, strides=1), # 第一层卷积 6个3x3
    layers.MaxPooling2D(pool_size=2, strides=2), # 宽高减半的池化层
    layers.ReLU(), #激活函数
    layers.Conv2D(16, kernel_size=3, strides=1), # 第二层卷积 16个3x3
    layers.MaxPooling2D(pool_size=2, strides=2), # 宽高减半的池化层
    layers.ReLU(), #激活函数
    layers.Flatten(), # 打平层，方便全连接处理
    
    layers.Dense(120, activation='relu'), # 120个结点的全连接层
    layers.Dense(84, activation='relu'), # 全连接层 84节点
    layers.Dense(10), # 全连接层 10结点
])

network.build(input_shape=(4, 28, 28, 1))
# 统计网络信息
network.summary()

# 创建损失函数的类，在实际计算中调用类的实例即可
criteon=losses.CategoricalCrossentropy(from_logits=True)

optimizer = optimizers.Adam(lr=0.01)

acc_meter = metrics.Accuracy()
loss_meter = metrics.Mean()

for step, (x,y) in enumerate(db):
    
    # 构建梯度记录环境
    with tf.GradientTape() as tape:
        # 插入通道维度, =>[b,28,28,1]
        x=tf.expand_dims(x, axis=3) # 增加维度
        # 向前计算,获得10类别的概率分布 [b, 784] = > [b,10]
        out = network(x)
        # 真实标签One-hot编码 [b]=>[b,10]
        y_onehot = tf.one_hot(y, depth=10)
        # 计算交叉熵损失函数，标量
        loss = criteon(y_onehot, out)
        loss_meter.update_state(loss)
        
        with summary_writer.as_default(): # 写入环境
            tf.summary.scalar('train-loss', float(loss), step=step)
      
    # 自动计算梯度
    grads = tape.gradient(loss, network.trainable_variables)
    # 自动更新参数
    optimizer.apply_gradients(zip(grads, network.trainable_variables))
    
    if step%100==0:
        
        print(step, 'loss:', loss_meter.result().numpy())
        loss_meter.reset_states()
        
     # evaluate
    if step % 500 == 0:
        # 记录预测正确的数量， 总样本数量
        correct, total=0,0
        for step, (x,y) in enumerate(ds_val):
            # 插入通道维数, => [b, 28, 28, 1]
            x=tf.expand_dims(x, axis=3)
            # 向前计算, 获得10类别的预测分布, [b, 784]=>[b,10]
            out = network(x)
            # 真实流程是先经过softmax再argmax
            # 但是由于softmax不改变元素大小的相对关系，故省去
            pred=tf.argmax(out, axis=-1)
            y=tf.cast(y, tf.int64)
            # 统计预测正确数量
            correct += float(tf.reduce_sum(tf.cast(tf.equal(pred, y), tf.float32)))
            # 统计预测样本总数
            total += x.shape[0]
            
            
        # 计算准确率
        print('test acc:',correct/total)
        
        val_images=x[:10]
        with summary_writer.as_default():
                tf.summary.scalar('test-acc', float(correct/total), step=step)
                tf.summary.image("val-onebyone-images:", val_images, max_outputs=9, step=step)



datasets: (60000, 28, 28) (60000,) 0 255
Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_39 (Conv2D)           multiple                  60        
_________________________________________________________________
max_pooling2d_38 (MaxPooling multiple                  0         
_________________________________________________________________
re_lu_38 (ReLU)              multiple                  0         
_________________________________________________________________
conv2d_40 (Conv2D)           multiple                  880       
_________________________________________________________________
max_pooling2d_39 (MaxPooling multiple                  0         
_________________________________________________________________
re_lu_39 (ReLU)              multiple                  0         
_________________________________________________________________
flatten_19 (

KeyboardInterrupt: 

# CIFAR10 实战

In [2]:
import  tensorflow as tf
from    tensorflow.keras import layers, optimizers, datasets, Sequential
import  os

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
tf.random.set_seed(2345)

conv_layers = [ # 5 units of conv + max pooling
    # unit 1
    layers.Conv2D(64, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.Conv2D(64, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same'),

    # unit 2
    layers.Conv2D(128, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.Conv2D(128, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same'),

    # unit 3
    layers.Conv2D(256, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.Conv2D(256, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same'),

    # unit 4
    layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same'),

    # unit 5
    layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same')

]



def preprocess(x, y):
    # [0~1]
    x = 2*tf.cast(x, dtype=tf.float32) / 255.-1
    y = tf.cast(y, dtype=tf.int32)
    return x,y


(x,y), (x_test, y_test) = datasets.cifar10.load_data()
y = tf.squeeze(y, axis=1)
y_test = tf.squeeze(y_test, axis=1)
print(x.shape, y.shape, x_test.shape, y_test.shape)


train_db = tf.data.Dataset.from_tensor_slices((x,y))
train_db = train_db.shuffle(1000).map(preprocess).batch(128)

test_db = tf.data.Dataset.from_tensor_slices((x_test,y_test))
test_db = test_db.map(preprocess).batch(64)

sample = next(iter(train_db))
print('sample:', sample[0].shape, sample[1].shape,
      tf.reduce_min(sample[0]), tf.reduce_max(sample[0]))


def main():

    # [b, 32, 32, 3] => [b, 1, 1, 512]
    conv_net = Sequential(conv_layers)

    fc_net = Sequential([
        layers.Dense(256, activation=tf.nn.relu),
        layers.Dense(128, activation=tf.nn.relu),
        layers.Dense(10, activation=None),
    ])

    conv_net.build(input_shape=[None, 32, 32, 3])
    fc_net.build(input_shape=[None, 512])
    conv_net.summary()
    fc_net.summary()
    optimizer = optimizers.Adam(lr=1e-4)

    # [1, 2] + [3, 4] => [1, 2, 3, 4]
    variables = conv_net.trainable_variables + fc_net.trainable_variables

    for epoch in range(50):

        for step, (x,y) in enumerate(train_db):

            with tf.GradientTape() as tape:
                # [b, 32, 32, 3] => [b, 1, 1, 512]
                out = conv_net(x)
                # flatten, => [b, 512]
                out = tf.reshape(out, [-1, 512])
                # [b, 512] => [b, 10]
                logits = fc_net(out)
                # [b] => [b, 10]
                y_onehot = tf.one_hot(y, depth=10)
                # compute loss
                loss = tf.losses.categorical_crossentropy(y_onehot, logits, from_logits=True)
                loss = tf.reduce_mean(loss)

            grads = tape.gradient(loss, variables)
            optimizer.apply_gradients(zip(grads, variables))

            if step %100 == 0:
                print(epoch, step, 'loss:', float(loss))



        total_num = 0
        total_correct = 0
        for x,y in test_db:

            out = conv_net(x)
            out = tf.reshape(out, [-1, 512])
            logits = fc_net(out)
            prob = tf.nn.softmax(logits, axis=1)
            pred = tf.argmax(prob, axis=1)
            pred = tf.cast(pred, dtype=tf.int32)

            correct = tf.cast(tf.equal(pred, y), dtype=tf.int32)
            correct = tf.reduce_sum(correct)

            total_num += x.shape[0]
            total_correct += int(correct)

        acc = total_correct / total_num
        print(epoch, 'acc:', acc)



# if __name__ == '__main__':
#     main()
main()

(50000, 32, 32, 3) (50000,) (10000, 32, 32, 3) (10000,)
sample: (128, 32, 32, 3) (128,) tf.Tensor(-1.0, shape=(), dtype=float32) tf.Tensor(1.0, shape=(), dtype=float32)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           multiple                  1792      
_________________________________________________________________
conv2d_11 (Conv2D)           multiple                  36928     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 multiple                  0         
_________________________________________________________________
conv2d_12 (Conv2D)           multiple                  73856     
_________________________________________________________________
conv2d_13 (Conv2D)           multiple                  147584    
_________________________________________________________________
max_pooling2d_6 (Ma

KeyboardInterrupt: 

# 转置卷积的实现

In [6]:
import tensorflow as tf
# 创建4x4大小的输入
x=tf.range(16)+1
x=tf.reshape(x, [1,4,4,1])
x=tf.cast(x, tf.float32)
# 创建3x3的卷积核
w=tf.constant([[-1,2,-3.],[4,-5,6],[-7,8,-9]])
w=tf.expand_dims(w, axis=2)
w=tf.expand_dims(w, axis=3)
# 普通卷积运算
out=tf.nn.conv2d(x,w,strides=1,padding='VALID')
out
# 恢复4x4的大小
xx=tf.nn.conv2d_transpose(out,w,strides=1,padding='VALID',output_shape=[1,4,4,1])


# CIFAR10与ResNet18实战