In [2]:
# 常见网络类层
# 在tf.keras.layers命名空间中提供了许多大量的常见网络层的类,
# 例如 全连接层、激活函数层、池化层、卷积层、循环神经网络层等
# 对于这些网络层类只需要创建时指定相关参数，并且调用__call__方法即可完成向前计算
# 在__call__方法中，Keras会自动调用每个层的向前传播逻辑，这些逻辑一般实现在类的call函数中

# 搭建Softmax层 利用tf.nn.softmax和利用layers.Soiftmax(axis)类搭建，axis为指定Softmax的维度

import tensorflow as tf
# 导入keras模型
from tensorflow import keras
from tensorflow.keras import layers # 导入常见网络层类
# 创建Softmax层
x = tf.constant([2.,1.,0.1]) # 创建输入张量
layer = layers.Softmax(axis=-1) # 创建Softmax层
out = layer(x)
out

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6590012 , 0.24243298, 0.09856589], dtype=float32)>

In [3]:
# 利用tf.nn.softmax()函数完成计算
out = tf.nn.softmax(x) # 调用softmax函数完成向前计算
out 

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6590012 , 0.24243298, 0.09856589], dtype=float32)>

In [ ]:
###########################################################################################################

In [9]:
# 网络容器
# 当网络层数变得非常多的时候可以利用网络容器Sequential将多个网络层封装成一个
# 大网络模型，只需要调用网络模型的实例一次即可完成数据从第一层到最末层的顺序传播运算。
# 导入Sequential容器
from tensorflow.keras import layers, Sequential
network = Sequential([ # 封装成一个网络
    layers.Dense(3, activation=None), # 全连接层，此处不使用激活函数
    layers.ReLU(), # 激活函数层
    layers.Dense(2, activation=None), # 全连接层，此处不适用激活函数
    layers.ReLU(), # 激活函数层
])
x = tf.random.normal([4, 3])
out = network(x) # 输入从第一层开始， 逐层传播至输出层，并返回输出层的输出
out

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.      , 0.      ],
       [0.      , 0.      ],
       [0.      , 0.      ],
       [0.      , 0.728432]], dtype=float32)>

In [ ]:
# 利用add方法添加新的网络层，实现动态创建网络的功能
layers_num = 2 # 堆叠两次
network = Sequential([]) # 先创建空的网络容器