In [1]:
# 利用张量的方式实现全连接层

import tensorflow as tf 

# O = X@W+b
# 创建w,b张量
x = tf.random.normal([2, 784])
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
o1 = tf.matmul(x, w1) + b1 # x@w1+b
o1 = tf.nn.relu(o1)  # o1 = relu(x@w1+b)
o1

<tf.Tensor: shape=(2, 256), dtype=float32, numpy=
array([[0.        , 1.8398099 , 0.5363637 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 2.8802996 , 0.        ,
        0.7188273 , 0.        , 0.        , 0.        , 0.        ,
        0.57357943, 0.        , 0.        , 0.        , 2.2294762 ,
        0.        , 0.37645876, 0.        , 1.1180384 , 1.0756507 ,
        2.9940948 , 1.6736183 , 0.14751232, 0.        , 0.        ,
        0.7602004 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 3.3515143 , 0.        , 0.        , 0.        ,
        2.7704768 , 0.        , 0.        , 0.36631477, 0.        ,
        3.5488322 , 1.0670028 , 0.17685246, 0.        , 0.09324336,
        0.        , 2.623207  , 0.        , 0.        , 0.        ,
        0.        , 2.3191936 , 0.        , 1.6952323 , 0.        ,
        0.        , 0.        , 2.797187  , 0.        , 0.        ,
        5.6445613 , 1.9348626 , 0.        , 2.7998977 , 0.        

In [2]:
x=tf.random.normal([4, 28*28])
from tensorflow.keras import layers # 导入层模块
fc = layers.Dense(512, activation=tf.nn.relu)
h1 = fc(x)
h1

<tf.Tensor: shape=(4, 512), dtype=float32, numpy=
array([[0.        , 2.0082371 , 0.        , ..., 0.06216598, 0.6932498 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.0911157 , 0.8825047 ,
        0.        ],
       [0.        , 0.24756597, 0.6961701 , ..., 0.        , 2.0832436 ,
        0.8864894 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.34938884,
        0.        ]], dtype=float32)>

In [3]:
x=tf.random.normal([2, 28*28])
from tensorflow.keras import layers # 导入层模块
fc = layers.Dense(256, activation=tf.nn.relu)
h1 = fc(x)
h1

<tf.Tensor: shape=(2, 256), dtype=float32, numpy=
array([[0.00000000e+00, 3.71376276e-01, 0.00000000e+00, 9.50344741e-01,
        0.00000000e+00, 6.98700845e-01, 0.00000000e+00, 9.43213344e-01,
        1.74734473e+00, 6.15239859e-01, 2.33746052e-01, 0.00000000e+00,
        3.23016357e+00, 6.11578286e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.52057064e-01, 2.66546607e-01,
        7.66930163e-01, 8.09993863e-01, 9.49565619e-02, 7.18796626e-02,
        8.38390231e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.61539698e+00, 0.00000000e+00, 0.00000000e+00,
        2.52997428e-01, 0.00000000e+00, 8.14029276e-01, 1.06039381e+00,
        1.68269300e+00, 1.42331767e+00, 0.00000000e+00, 1.97048903e-01,
        1.13729441e+00, 1.51842207e-01, 0.00000000e+00, 1.98231268e+00,
        0.00000000e+00, 3.28703225e-01, 6.59187436e-01, 0.00000000e+00,
        1.63654971e+00, 5.10136604e-01, 4.45584059e-01, 0.00000000e+00,
        0.0000

In [4]:
fc.kernel # 获取Dense类的权值矩阵

<tf.Variable 'dense_1/kernel:0' shape=(784, 256) dtype=float32, numpy=
array([[-0.05607687, -0.04172711, -0.0464981 , ...,  0.0348444 ,
         0.06602745, -0.02593955],
       [ 0.02282723, -0.04524446,  0.03287929, ..., -0.02685129,
         0.02086899,  0.02730498],
       [-0.04796496, -0.04405752,  0.03131269, ...,  0.06309843,
        -0.02599879, -0.02232345],
       ...,
       [-0.06215498,  0.02123313, -0.00548182, ...,  0.00607321,
         0.05191955,  0.07165468],
       [-0.01390878, -0.00232316, -0.05913875, ...,  0.05565313,
        -0.01666477,  0.05319232],
       [-0.05458195, -0.01469821, -0.06871158, ...,  0.03315981,
         0.03784071, -0.0019561 ]], dtype=float32)>

In [5]:
fc.bias

<tf.Variable 'dense_1/bias:0' shape=(256,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 

In [6]:
fc.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(784, 256) dtype=float32, numpy=
 array([[-0.05607687, -0.04172711, -0.0464981 , ...,  0.0348444 ,
          0.06602745, -0.02593955],
        [ 0.02282723, -0.04524446,  0.03287929, ..., -0.02685129,
          0.02086899,  0.02730498],
        [-0.04796496, -0.04405752,  0.03131269, ...,  0.06309843,
         -0.02599879, -0.02232345],
        ...,
        [-0.06215498,  0.02123313, -0.00548182, ...,  0.00607321,
          0.05191955,  0.07165468],
        [-0.01390878, -0.00232316, -0.05913875, ...,  0.05565313,
         -0.01666477,  0.05319232],
        [-0.05458195, -0.01469821, -0.06871158, ...,  0.03315981,
          0.03784071, -0.0019561 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(256,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,